# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Jo Albright'
tagline:          'DESIGNER  .  DEVELOPER  .  ï£¿NERD'
description:      ''
url:              http://jo2.co
baseurl:          /
blogurl:          /blog/

author:
  name:           'Jo Albright'
  url:            https://twitter.com/joalbright

gems: ['jekyll-paginate','jekyll-gist']

paginate:         5
paginate_path:    '/blog/page:num/'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/joalbright
